# Generated by Django 3.2.7 on 2021-09-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='conteudo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
    ]
