# Generated by Django 3.2.7 on 2021-09-28 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
        ('edu', '0003_auto_20210928_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(db_index=True, max_length=255, verbose_name='Matrícula')),
                ('estado_civil', models.CharField(choices=[['Solteiro', 'Solteiro'], ['Casado', 'Casado'], ['União Estável', 'União Estável'], ['Divorciado', 'Divorciado'], ['Viúvo', 'Viúvo']], max_length=20, null=True)),
                ('logradouro', models.CharField(max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=255, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=255, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=255, null=True, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=255, null=True, verbose_name='Cidade')),
                ('nome_pai', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Pai')),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável')),
                ('telefone_secundario', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Secundário')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('numero_rg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do RG')),
                ('uf_emissao_rg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado Emissor')),
                ('periodo_letivo', models.PositiveIntegerField(choices=[[1, '1'], [2, '2']], verbose_name='Período de Ingresso')),
                ('data_matricula', models.DateTimeField(auto_now_add=True, verbose_name='Data da Matrícula')),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_edu_set', to='comum.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Matricula de Aluno',
                'verbose_name_plural': 'Matriculas de Alunos',
                'ordering': ('-matricula',),
            },
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
