# Generated by Django 3.2.7 on 2021-09-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_auto_20210928_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunomatricula',
            options={'verbose_name': 'Matricula de Aluno', 'verbose_name_plural': 'Matriculas de Alunos'},
        ),
        migrations.AddField(
            model_name='alunomatricula',
            name='curso',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='matricula_edu_set', to='edu.curso', verbose_name='Curso'),
        ),
    ]
