# Generated by Django 3.2.7 on 2021-09-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_auto_20210928_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequencialMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=255)),
                ('contador', models.PositiveIntegerField()),
            ],
        ),
    ]
