# Generated by Django 3.2.7 on 2021-09-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_sequencialmatricula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequencialmatricula',
            options={'verbose_name': 'Sequencial de Matricula', 'verbose_name_plural': 'Sequencial de Matriculas'},
        ),
        migrations.AlterField(
            model_name='alunomatricula',
            name='matricula',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Matrícula'),
        ),
    ]
